- name: Ensure folders exist
  file:
    path: "/opt/{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
    - .screenly
    - .config

- name: Copy Screenly default config
  copy:
    owner: root
    group: root
    src: screenly.conf
    dest: /etc/screenly/screenly.conf
    force: no

- name: Remove deprecated parameter "listen"
  lineinfile:
    regexp: '^.*listen.*'
    state: absent
    dest: /etc/screenly/screenly.conf




- name: Install pip dependencies
  pip: requirements=/opt/screenly/requirements.txt

- name: Create default assets database if does not exists
  copy:
    owner: root
    group: root
    src: screenly.db
    dest: /opt/.screenly/screenly.db
    force: no

- name: Run database migration
  become: no
  command: python /opt/screenly/bin/migrate.py
  register: migrate

- debug: msg="{{ migrate.stdout }}"

- name: Copy screenly_utils.sh
  copy:
    src: screenly_utils.sh
    dest: /usr/local/bin/screenly_utils.sh
    mode: 0755
    owner: root
    group: root

- cron:
    name: Cleanup screenly_assets
    minute: 0
    hour: 1
    job: "/usr/local/bin/screenly_utils.sh cleanup"
    user: root

- name: Copy screenly_overrides
  copy:
    src: screenly_overrides
    dest: /etc/sudoers.d/screenly_overrides
    mode: 0440
    owner: root
    group: root

- name: Copy screenly systemd units
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
  with_items: "{{ screenly_systemd_units }}"

- name: Enable screenly systemd services
  command: systemctl enable {{ item }} chdir=/etc/systemd/system
  with_items: "{{ screenly_systemd_units }}"
