---
# Enable Apache2
- name: Check screenly.conf
  command: cat /etc/screenly/screenly.conf
  register: config

- set_fact: no_ssl="{{config.stdout.find('use_ssl = True') == -1}}"

- name: Installs Apache2
  apt:
    name: 
    state: present
    update_cache: yes

- name: Cleans up default config
  file:
    path: /etc/apache2/sites-enabled/default
    state: absent

- name: Installs apache2 config
  copy:
    src: apache2.conf
    dest:  /etc/apache2/sites-enabled/screenly.conf
    mode: 644
    owner: root
    group: root
    force: no

- name: Modifies screenly-web service to only listen on localhost
  lineinfile:
    regexp: '^.*LISTEN.*'
    state: absent
    dest: /etc/systemd/system/screenly-web.service
  when: no_ssl

# Disable Apache2
- name: Remove Apache2
  apt:
    name: apache2
    state: absent
    update_cache: yes
  tags:
    - disable-apache2

- name: Remove apache2 config
  file:
    path:  /etc/apache2/sites-enabled/screenly.conf
    state: absent
  tags:
    - disable-apache2

- name: Turns off the ssl mode
  replace:
    replace: 'use_ssl = False'
    regexp: '^.*use_ssl.*'
    dest: /opt/.screenly/screenly.conf
  tags:
    - disable-apache2

- name: Modifies screenly-web service to listen on default gateway
  lineinfile:
    insertafter: '^\[Service\]'
    regexp: '^\[Service\]*;'
    line: Environment=LISTEN=0.0.0.0
    dest: /etc/systemd/system/screenly-web.service
  notify:
    - reload systemctl
    - restart-screenly-websocket_server_layer
    - restart-screenly-server
  tags:
    - disable-apache2
