
#- name: test for available disk space
#  assert:
#    that:
#     - "{{ item.size_available > 500 * 1000 * 1000 }}" # 500Mb
#  when: "{{ item.mount == '/' }}"
#  with_items: "{{ ansible_mounts }}"



# Sometimes in some packages there are no necessary files.
# They are required to install pip dependencies.
# In this case we need to reinstall the packages.
- name: Check if cdefs.h exists
  stat:
    path: /usr/include/arm-linux-gnueabihf/sys/cdefs.h
  register: cdefs

- set_fact: cdefs_exist="{{cdefs.stat.exists}}"

- name: Remove libc6-dev
  apt:
    name: libc6-dev
    state: absent
  when: not cdefs_exist

- name: Install libc6-dev
  apt:
    name: libc6-dev
    state: present
    update_cache: yes
  when: not cdefs_exist

- name: Check if cc1plus exists
  stat:
    path: /usr/lib/gcc/arm-linux-gnueabihf/4.9/cc1plus
  register: cc1plus

- set_fact: cc1plus_exist="{{cc1plus.stat.exists}}"

- name: Remove build-essential
  apt:
    name: build-essential
    state: absent
  when: not cc1plus_exist

- name: Install build-essential
  apt:
    name: build-essential
    state: present
    update_cache: yes
  when: not cc1plus_exist

- name: Install Screenly dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - console-data
    - libffi-dev
    - libssl-dev
    - matchbox
    - python-dev
    - python-netifaces
    - python-simplejson
    - sqlite3
    - systemd
    - x11-xserver-utils
    - xserver-xorg

- name: Install systemd-sysv on Wheezy
  command: bash -c 'echo "Yes, do as I say!" | apt-get install -y --force-yes systemd-sysv'
  when: ansible_distribution_release == "wheezy"

- name: Remove deprecated apt dependencies
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - supervisor
    - lightdm
    - lightdm-gtk-greeter
    - dphys-swapfile

- name: Perform system upgrade
  apt:
    upgrade: dist
  tags:
    - system-upgrade

- name: Clean up unused packages
  command: apt-get -y autoremove
  tags:
    - system-upgrade

- name: Remove deprecated pip dependencies
  pip:
    name: supervisor
    state: absent

- name: Copy in rc.local
  copy:
    src: rc.local
    dest: /etc/rc.local
    mode: 0755
    owner: root
    group: root

- name: Copy in 01_nodoc
  copy:
    src: 01_nodoc
    dest: /etc/dpkg/dpkg.cfg.d/01_nodoc
    mode: 0644
    owner: root
    group: root

- name: Copy in evdev
  copy:
    src: 10-evdev.conf
    dest: /usr/share/X11/xorg.conf.d/10-evdev.conf
    mode: 0644
    owner: root
    group: root

- name: Disable DPMS
  copy:
    src: 10-serverflags.conf
    dest: /usr/share/X11/xorg.conf.d/10-serverflags.conf
    mode: 0644
    owner: root
    group: root

- name: Clear out X11 configs (disables touchpad and other unnecessary things)
  file:
    path: "/usr/share/X11/xorg.conf.d/{{ item }}"
    state: absent
  with_items:
    - 50-synaptics.conf
    - 10-quirks.conf
    - 50-wacom.conf

- name: Disable swap
  command: /sbin/swapoff --all removes=/var/swap

- name: Remove swapfile from disk
  file:
    path: /var/swap
    state: absent
