- name: Install Screenly
  hosts: all
  user: root
  become: yes

  handlers:
    - name: restart-apache2
      service:
        name: apache2
        state: restarted

    - name: reload systemctl
      command: systemctl daemon-reload

    - name: restart-screenly-websocket_server_layer
      command: systemctl restart screenly-websocket_server_layer.service

    - name: restart-screenly-server
      command: systemctl restart screenly-web.service

    - name: restart-x-server
      command: "systemctl restart {{ item }}"
      with_items:
      - X.service
      - matchbox.service

    - name: restart-screenly-viewer
      command: systemctl restart screenly-viewer.service

  roles:
    - system
    - network
    - screenly
    - ssl
    - apache2
